ARG RUBY_VERSION=3.4.7
FROM docker.io/library/ruby:$RUBY_VERSION-slim

WORKDIR /rails

# Install packages needed for development
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      curl \
      git \
      libpq-dev \
      libvips \
      libjemalloc2 \
      libyaml-dev \
      nodejs \
      npm \
      pkg-config \
      postgresql-client \
      watchman && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN npm install -g tailwindcss

ENV BUNDLE_PATH="/usr/local/bundle" \
    RAILS_ENV="development"

# Install all gems (including development/test)
COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

RUN bundle exec bootsnap precompile --gemfile app/ lib/

EXPOSE 3000

CMD ["./bin/dev"]
